using rharel.M3PD.Agency.State;
using rharel.M3PD.Agency.System;

namespace rharel.M3PD.Agency.Modules
{
    /// <summary>
    /// A stub implementation of the <see cref="SUModule"/>.
    /// </summary>
    public sealed class SUStub: SUModule
    {
        /// <summary>
        /// Leaves the state untouched.
        /// </summary>
        /// <param name="recent_activity">
        /// The recent activity report, as was generated by 
        /// <see cref="RAPModule"/>.
        /// </param>
        /// <param name="current_activity">
        /// The current activity report, as was generated by
        /// <see cref="CAPModule"/>.
        /// </param>
        /// <param name="system_activity">
        /// A snapshot the system's own current activity.
        /// </param>
        /// <param name="state_mutator">
        /// Allows mutation of state components.
        /// </param>
        public override void PerformUpdate(
            RecentActivity recent_activity,
            CurrentActivity current_activity,
            SystemActivity system_activity,
            StateMutator state_mutator) { }

        /// <summary>
        /// Returns a string that represents this instance.
        /// </summary>
        /// <returns>A human-readable string.</returns>
        public override string ToString()
        {
            return $"{nameof(SUStub)}{{ " +
                   $"{nameof(State)} = {State} }}";
        }
    }
}
